language: php

install: composer update --dev
script: ./vendor/bin/phpunit

jobs:
  include:
    - stage: Unit tests
      php: 5.6
    - stage: Unit tests
      php: 7.0
    - stage: Unit tests
      php: 7.1
    - stage: Unit tests
      php: 7.2
    - stage: Unit tests
      php: 7.3
